HOME_LOGO = 'div.app_logo'
BURGER_MENU = '#react-burger-menu-btn'
LOGOUT_BUTTON = '#logout_sidebar_link'
ERROR_MESSAGE = '[data-test="error"]'
PRODUCT_SORT_DROPDOWN = 'select.product_sort_container'
PRODUCT_NAME_LIST = '//div[@class="inventory_list"]//div[contains(@class,"inventory_item_name")]'
PRODUCT_PRICE_LIST = '//div[@class="inventory_list"]//div[contains(@class,"inventory_item_price")]'